### ISSUE TITLE
ФИЧА - скриншот объекта на странице

### ISSUE THREAD

**Issue by dimadem** [dimadem/pmf#5]
- добавить кнопку на страницу tree 
- по нажатии на кнопку должно скачиваться квадратное изображение (дерева и фона - всей сцены) в формате .png (500 на 500)

**Comment by domosedoff** [comment]
Кнопку скриншота сделал - работает, но сохраняет не в квадрате, а с теми же пропорциями что и во фрейме. Предлагаю по возможности сделать в верстке наше дерево в квадратном фрейме.

**Comment by dimadem** [comment]
> Кнопку скриншота сделал - работает, но сохраняет не в квадрате, а с теми же пропорциями что и во фрейме. Предлагаю по возможности сделать в верстке наше дерево в квадратном фрейме.

#11
